# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='last_request_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
